import { Pokemon } from "../app/interfaces/interfaces";

export const potion: Item = {
  name: "potion",
  type: "heal",
  value: 20,
  image:
    "https://archives.bulbagarden.net/media/upload/thumb/9/99/Potion_SV.png/1200px-Potion_SV.png",
};

export const superPotion: Item = {
  name: "super potion",
  type: "heal",
  value: 50,
  image:
    "https://archives.bulbagarden.net/media/upload/3/30/Bag_Super_Potion_SV_Sprite.png",
};

export const lucario: Pokemon = {
  name: "Lucario",
  type: {
    type1: "fighting",
    type2: "steel",
    resistance: ["Normal", "Ice", "Rock", "Dark", "Steel"],
    weakness: ["Fire", "Ground", "Fighting"],
  },
  image:
    "https://img.pokemondb.net/sprites/black-white/anim/normal/lucario.gif",
  imageBack:
    "https://img.pokemondb.net/sprites/black-white/anim/back-normal/lucario.gif",
  condition: null,
  stats: {
    lvl: 50,
    hp: 140,
    attack: 145,
    defense: 88,
    specialAttk: 105,
    specialDef: 88,
    speed: 112,
  },
  stageMods: {
    attack: 0,
    defense: 0,
    specialAttk: 0,
    specialDef: 0,
    speed: 0,
    evasion: 0,
    accuracy: 0,
  },
  refStats: {
    lvl: 50,
    hp: 140,
    attack: 145,
    defense: 88,
    specialAttk: 105,
    specialDef: 88,
    speed: 112,
  },
  moves: [
    {
      name: "Close Combat",
      power: 120,
      type: "fighting",
      accuracy: 100,
      priority: 0,
      stageMod: [
        { name: "attack", amount: -1, target: "self" },
        { name: "defense", amount: -1, target: "self" },
      ],
      condition: { name: null, chance: null },
      effects: { name: null, chance: null },
      animationType: "physical",
      description:
        "The user fights the target up close without guarding itself. It also cuts the user's Defense and Sp. Def.",
      hitType: "physical",
      contact: true,
      pp: 5,
    },
    {
      name: "Aura Sphere",
      power: 90,
      type: "fighting",
      accuracy: 100,
      priority: 0,
      stageMod: [{ name: null, amount: null, target: null }],
      condition: { name: null, chance: null },
      effects: { name: null, chance: null },
      animationType: "special",
      description:
        "The user lets loose a blast of aura power from deep within its body at the target. This attack never misses.",
      hitType: "special",
      contact: false,
      pp: 20,
    },
    {
      name: "Swords Dance",
      power: 0,
      type: "normal",
      accuracy: 100,
      priority: 0,
      stageMod: [{ name: "attack", amount: 2, target: "self" }],
      condition: { name: null, chance: null },
      effects: { name: null, chance: null },
      animationType: "status-self",
      description:
        "A frenetic dance to uplift the fighting spirit. It sharply raises the user's Attack stat.",
      hitType: "status",
      contact: false,
      pp: 20,
    },
    {
      name: "Nasty Plot",
      power: 0,
      type: "dark",
      accuracy: 100,
      priority: 0,
      stageMod: [{ name: "specialAttk", amount: 2, target: "self" }],
      condition: { name: null, chance: null },
      effects: { name: null, chance: null },
      animationType: "status-self",
      description:
        "The user stimulates its brain by thinking bad thoughts. This sharply raises the user's Sp. Atk.",
      hitType: "status-self",
      contact: false,
      pp: 20,
    },
  ],
};
export const charizard: Pokemon = {
  name: "Charizard",
  type: {
    type1: "fire",
    type2: "flying",
    resistance: ["Bug", "Grass", "Fighting", "Fire", "Steel"],
    weakness: ["Rock", "Water", "Electric"],
  },
  image:
    "https://img.pokemondb.net/sprites/black-white/anim/normal/charizard.gif",
  imageBack:
    "https://img.pokemondb.net/sprites/black-white/anim/back-normal/charizard.gif",
  condition: null,
  stats: {
    lvl: 50,
    hp: 153,
    attack: 104,
    defense: 98,
    specialAttk: 129,
    specialDef: 105,
    speed: 120,
  },
  stageMods: {
    attack: 0,
    defense: 0,
    specialAttk: 0,
    specialDef: 0,
    speed: 0,
    evasion: 0,
    accuracy: 0,
  },
  refStats: {
    lvl: 50,
    hp: 153,
    attack: 103,
    defense: 97,
    specialAttk: 129,
    specialDef: 105,
    speed: 118,
  },
  moves: [
    {
      name: "Flame Thrower",
      power: 90,
      type: "fire",
      accuracy: 100,
      priority: 0,
      stageMod: [{ name: null, amount: null, target: null }],
      condition: { name: "burn", chance: 10 },
      effects: { name: null, chance: null },
      animationType: "special",
      description:
        "The target is scorched with an intense blast of fire. This may also leave the target with a burn.",
      hitType: "special",
      contact: false,
      pp: 15,
    },
    {
      name: "Fire Fang",
      power: 65,
      type: "fire",
      accuracy: 95,
      priority: 0,
      stageMod: [{ name: null, amount: null, target: null }],
      condition: { name: "burn", chance: 10 },
      effects: { name: "flinch", chance: 20 },
      animationType: "physical",
      description:
        "The user bites with flame-cloaked fangs. This may also make the target flinch or leave it with a burn.",
      hitType: "physical",
      contact: true,
      pp: 15,
    },
    {
      name: "Sword Dance",
      power: 0,
      type: "normal",
      accuracy: 100,
      priority: 0,
      stageMod: [{ name: "attack", amount: 2, target: "self" }],
      condition: { name: null, chance: null },
      effects: { name: null, chance: null },
      animationType: "status-self",
      description:
        "A frenetic dance to uplift the fighting spirit. It sharply raises the user's Attack stat.",
      hitType: "status-self",
      contact: false,
      pp: 20,
    },
    {
      name: "Smoke Screen",
      power: 0,
      type: "normal",
      accuracy: 100,
      priority: 0,
      stageMod: [{ name: "accuracy", amount: -1, target: "opponent" }],
      condition: { name: null, chance: null },
      effects: { name: null, chance: null },
      animationType: "status-opponent",
      description:
        "The user releases an obscuring cloud of smoke or ink. It reduces the target's accuracy.",
      hitType: "status-opponent",
      contact: false,
      pp: 20,
    },
  ],
};
export const venusaur: Pokemon = {
  name: "Venusaur",
  type: {
    type1: "grass",
    type2: "poison",
    resistance: ["Fighting", "Water", "Electric", "Grass", "Fairy"],
    weakness: ["Fire", "Ice", "Flying", "Psychic"],
  },

  image:
    "https://img.pokemondb.net/sprites/black-white/anim/normal/venusaur.gif",
  imageBack:
    "https://img.pokemondb.net/sprites/black-white/anim/back-normal/venusaur.gif",
  condition: null,
  stats: {
    lvl: 50,
    hp: 155,
    attack: 102,
    defense: 103,
    specialAttk: 120,
    specialDef: 120,
    speed: 100,
  },

  stageMods: {
    attack: 0,
    defense: 0,
    specialAttk: 0,
    specialDef: 0,
    speed: 0,
    evasion: 0,
    accuracy: 0,
  },
  refStats: {
    lvl: 50,
    hp: 155,
    attack: 100,
    defense: 123,
    specialAttk: 122,
    specialDef: 120,
    speed: 80,
  },
  moves: [
    {
      name: "Razor Leaf",
      power: 55,
      type: "grass",
      accuracy: 95,
      priority: 0,
      stageMod: [{ name: null, amount: null, target: null }],
      condition: { name: null, chance: null },
      effects: { name: null, chance: null },
      animationType: "physical",
      description:
        "Sharp-edged leaves are launched to slash at opposing Pokémon. Critical hits land more easily.",
      hitType: "physical",
      contact: false,
      pp: 25,
    },
    {
      name: "Quick Attack",
      power: 40,
      type: "normal",
      accuracy: 100,
      priority: 1,
      stageMod: [{ name: null, amount: null, target: null }],
      condition: { name: null, chance: null },
      effects: { name: null, chance: null },
      animationType: "physical",
      description:
        "The user lunges at the target at a speed that makes it almost invisible. This move always goes first!",
      hitType: "physical",
      contact: true,
      pp: 30,
    },
    {
      name: "Vine Whip",
      power: 45,
      type: "grass",
      accuracy: 100,
      priority: 0,
      stageMod: [{ name: null, amount: null, target: null }],
      condition: { name: null, chance: null },
      effects: { name: null, chance: null },
      animationType: "physical",
      description:
        "The target is struck with slender, whiplike vines to inflict damage.",
      hitType: "physical",
      contact: true,
      pp: 25,
    },
    {
      name: "Bulk Up",
      power: null,
      type: "fighting",
      accuracy: 100,
      priority: 0,
      stageMod: [
        { name: "attack", amount: 1, target: "self" },
        { name: "defense", amount: 1, target: "self" },
      ],
      condition: { name: null, chance: null },
      effects: { name: null, chance: null },
      animationType: "status-self",
      description:
        "The user tenses its muscles to bulk up its body, raising both its Attack and Defense stats.",
      hitType: "status-self",
      contact: false,
      pp: 20,
    },
  ],
};
export const pikachu: Pokemon = {
  name: "Pikachu",
  type: {
    type1: "electric",
    type2: null,
    resistance: ["Electric", "Flying", "Steel"],
    weakness: ["Ground"],
  },
  image:
    "https://img.pokemondb.net/sprites/black-white/anim/normal/pikachu.gif",
  imageBack:
    "https://img.pokemondb.net/sprites/black-white/anim/back-normal/pikachu.gif",
  stats: {
    lvl: 50,
    hp: 102,
    attack: 68,
    defense: 53,
    specialAttk: 65,
    specialDef: 65,
    speed: 108,
  },
  stageMods: {
    attack: 0,
    defense: 0,
    specialAttk: 0,
    specialDef: 0,
    speed: 0,
    evasion: 0,
    accuracy: 0,
  },
  refStats: {
    lvl: 50,
    hp: 102,
    attack: 68,
    defense: 53,
    specialAttk: 65,
    specialDef: 65,
    speed: 108,
  },
  moves: [
    {
      name: "Tackle",
      power: 40,
      type: "normal",
      accuracy: 100,
      priority: 0,
      stageMod: [{ name: null, amount: null, target: null }],
      condition: { name: null, chance: null },
      effects: { name: null, chance: null },
      animationType: "physical",
      description:
        "A physical attack in which the user charges and slams into the target with its whole body.",
      hitType: "physical",
      contact: true,
      pp: 35,
    },
    {
      name: "Thunderbolt",
      power: 90,
      type: "electric",
      accuracy: 100,
      priority: 0,
      stageMod: [
        {
          name: null,
          amount: null,
          target: null,
        },
      ],
      condition: {
        name: "paralysis",
        chance: 10,
      },
      effects: {
        name: null,
        chance: null,
      },
      animationType: "special",
      description:
        "A strong electric attack that may also leave the target paralyzed. It has a one-in-ten chance of paralyzing the target.",
      hitType: "special",
      contact: false,
      pp: 15,
    },
    {
      name: "Extreme Speed",
      power: 80,
      type: "Normal",
      accuracy: 100,
      priority: 2,
      stageMod: [{ name: null, amount: null, target: null }],
      condition: { name: null, chance: null },
      effects: { name: null, chance: null },
      animationType: "physical",
      description:
        "The user charges the target at blinding speed. This move always goes first.",
      hitType: "physical",
      contact: true,
      pp: 5,
    },
    {
      name: "Calm Mind",
      power: null,
      type: "Psychic",
      accuracy: 100,
      priority: 0,
      stageMod: [
        { name: "specialAttack", amount: 1, target: "self" },
        { name: "specialDefense", amount: 1, target: "self" },
      ],
      condition: { name: null, chance: null },
      effects: { name: null, chance: null },
      animationType: "status-self",
      description:
        "The user quietly focuses its mind and calms its spirit to raise its Sp. Atk and Sp. Def stats.",
      hitType: "status-self",
      contact: false,
      pp: 20,
    },
  ],
};
export const blastoise: Pokemon = {
  name: "Blastoise",
  type: {
    type1: "water",
    type2: null,
    resistance: ["Steel", "Fire", "Water", "Ice"],
    weakness: ["Electric", "Grass"],
  },
  image:
    "https://img.pokemondb.net/sprites/black-white/anim/normal/blastoise.gif",
  imageBack:
    "https://img.pokemondb.net/sprites/black-white/anim/back-normal/blastoise.gif",
  condition: null,
  stats: {
    lvl: 50,
    hp: 158,
    attack: 103,
    defense: 130,
    specialAttk: 154,
    specialDef: 120,
    speed: 100,
  },
  stageMods: {
    attack: 0,
    defense: 0,
    specialAttk: 0,
    specialDef: 0,
    speed: 0,
    evasion: 0,
    accuracy: 0,
  },
  refStats: {
    lvl: 50,
    hp: 158,
    attack: 103,
    defense: 130,
    specialAttk: 154,
    specialDef: 120,
    speed: 100,
  },
  moves: [
    {
      name: "Hydro Pump",
      power: 110,
      type: "water",
      accuracy: 80,
      priority: 0,
      stageMod: [{ name: null, amount: null, target: null }],
      condition: { name: null, chance: null },
      effects: { name: null, chance: null },
      animationType: "special",
      description:
        "The target is blasted by a huge volume of water launched under great pressure.",
      hitType: "special",
      contact: false,
      pp: 5,
    },
    {
      name: "Ice Beam",
      power: 90,
      type: "ice",
      accuracy: 100,
      priority: 0,
      stageMod: [{ name: null, amount: null, target: null }],
      condition: {
        name: "freeze",
        chance: 10,
      },
      effects: { name: null, chance: null },
      animationType: "special",
      description:
        "The target is struck with an icy-cold beam of energy. This may also leave the target frozen.",
      hitType: "special",
      contact: false,
      pp: 10,
    },
    {
      name: "Rapid Spin",
      power: 50,
      type: "normal",
      accuracy: 100,
      priority: 0,
      stageMod: [{ name: null, amount: null, target: null }],
      condition: { name: null, chance: null },
      effects: { name: null, chance: null },
      animationType: "physical",
      description:
        "A spin attack that can also eliminate such moves as Bind, Wrap, Leech Seed, and Spikes.",
      hitType: "physical",
      contact: true,
      pp: 40,
    },
    {
      name: "Toxic",
      power: 0,
      type: "poison",
      accuracy: 90,
      priority: 0,
      stageMod: [{ name: null, amount: null, target: null }],
      condition: { name: null, chance: null },
      effects: { name: null, chance: null },
      animationType: "status",
      description:
        "A move that leaves the target badly poisoned. Its poison damage worsens every turn.",
      hitType: "status",
      contact: false,
      pp: 10,
    },
  ],
};
export const gengar: Pokemon = {
  name: "Gengar",
  type: {
    type1: "ghost",
    type2: "poison",
    resistance: ["Bug", "Poison"],
    weakness: ["Ground", "Dark", "Ghost"],
  },
  image: "https://img.pokemondb.net/sprites/black-white/anim/normal/gengar.gif",
  imageBack:
    "https://img.pokemondb.net/sprites/black-white/anim/back-normal/gengar.gif",
  condition: null,
  stats: {
    lvl: 50,
    hp: 130,
    attack: 85,
    defense: 75,
    specialAttk: 170,
    specialDef: 95,
    speed: 130,
  },
  stageMods: {
    attack: 0,
    defense: 0,
    specialAttk: 0,
    specialDef: 0,
    speed: 0,
    evasion: 0,
    accuracy: 0,
  },
  refStats: {
    lvl: 50,
    hp: 130,
    attack: 85,
    defense: 75,
    specialAttk: 170,
    specialDef: 95,
    speed: 130,
  },
  moves: [
    {
      name: "Shadow Ball",
      power: 80,
      type: "ghost",
      accuracy: 100,
      priority: 0,
      stageMod: [{ name: "defense", amount: -1, target: "opponent" }],
      condition: { name: null, chance: null },
      effects: { name: null, chance: null },
      animationType: "special",
      description:
        "The user hurls a shadowy blob at the target. This may also lower the target's Sp. Def stat.",
      hitType: "special",
      contact: false,
      pp: 15,
    },
    {
      name: "Sludge Bomb",
      power: 90,
      type: "poison",
      accuracy: 100,
      priority: 0,
      stageMod: [{ name: null, amount: null, target: null }],
      condition: {
        name: "poison",
        chance: 30,
      },
      effects: { name: null, chance: null },
      animationType: "special",
      description:
        "Unsanitary sludge is hurled at the target. This may also poison the target.",
      hitType: "special",
      contact: false,
      pp: 10,
    },
    {
      name: "Hypnosis",
      power: 0,
      type: "psychic",
      accuracy: 60,
      priority: 0,
      stageMod: [{ name: null, amount: null, target: null }],
      condition: {
        name: "sleep",
        chance: 100,
      },
      effects: { name: null, chance: null },
      animationType: "status",
      description:
        "The user employs hypnotic suggestion to make the target fall into a deep sleep.",
      hitType: "status",
      contact: false,
      pp: 20,
    },
    {
      name: "Destiny Bond",
      power: 0,
      type: "ghost",
      accuracy: 0,
      priority: 0,
      stageMod: [{ name: null, amount: null, target: null }],
      condition: { name: null, chance: null },
      effects: { name: "destinyBond", chance: null },
      animationType: "status",
      description:
        "When this move is used, if the user faints, the Pokémon that landed the knockout hit also faints.",
      hitType: "status",
      contact: false,
      pp: 5,
    },
  ],
};
